name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn analyze"
  acceptance:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: "yarn install"
      - uses: cypress-io/github-action@v2
        with:
          command: "yarn ci:test:acc"
  unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn ci:test:unit"
