name: test
on: [push]
jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: "yarn"
      - uses: cypress-io/github-action@v2
        with:
          command: "yarn test:acc"
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: "yarn"
      - run: "yarn test:unit"
